export enum ConfigKeys {
  FRONT_END_URL = 'FRONT_END_URL',
  FRONT_END_ADMIN_URL = 'FRONT_END_ADMIN_URL',
  MOODLE_URL = 'MOODLE_URL',
  LOCK_LOGIN_UNTIL = 'LOCK_LOGIN_UNTIL',
  LOCK_LOGIN_ATTEMPTS = 'LOCK_LOGIN_ATTEMPTS',
  SESSION_EXPIRATION = 'SESSION_EXPIRATION',
  PAYMENT_EXPIRATION = 'PAYMENT_EXPIRATION',
  PAYMENT_REDIRECT_URL = 'PAYMENT_REDIRECT_URL',
  LOGO_URL = 'LOGO_URL',
}
