export enum EducationLevel {
    PRIMARIA = 'PRIMARIA',
    BASICA_SECUNDARIA = 'BASICA SECUNDARIA',
    BACHILLERATO = 'BACHILLERATO',
    TECNICO = 'TECNICO',
    PROFESIONAL = 'PROFESIONAL',
    UNIVERSITARIO = 'UNIVERSITARIO',
    POSGRADO = 'POSGRADO',
    OTRO = 'OTRO',
}