export enum Template {
    RESET_PASSWORD = 'RESET_PASSWORD',
    COURSE_ENROLLMENT = 'COURSE_ENROLLMENT',
    CERTIFICATE = 'CERTIFICATE',
    REGISTER = 'REGISTER',
    UPLOAD_SUMMARY = 'UPLOAD_SUMMARY',
}